services:
  app:
    build: ./app

    ports:
      - "3000:3000"

    volumes:
      - ./app:/app

    command: npm start

  attacker:
    build: ./attacker

    ports:
      - "4000:4000"

    volumes:
      - ./attacker:/app
      - /app/node_modules

    command: npm start
